const app=document.querySelector('#app');
const toast=document.querySelector('#toast');
let catalogs=null;
let session=JSON.parse(localStorage.getItem('fenologia-session')||'null');
const assignments=JSON.parse(localStorage.getItem('fenologia-lot-varieties')||'{}');
const records=JSON.parse(localStorage.getItem('fenologia-records')||'[]');
const users=[
 {name:'Administrador Demo',dni:'12345678',role:'Administrador'},
 {name:'Supervisor Demo',dni:'11223344',role:'Supervisor'},
 {name:'Evaluador Demo',dni:'87654321',role:'Evaluador'}
];
const stages=Array.from({length:17},(_,i)=>`E${String(i+1).padStart(2,'0')}`);
const say=m=>{toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)};
const save=()=>localStorage.setItem('fenologia-records',JSON.stringify(records));
const options=a=>'<option value="">Seleccionar</option>'+a.map(x=>`<option>${x}</option>`).join('');
function login(){app.innerHTML=`<main class="login"><section class="card login-card"><div class="brand">🌱<h1>Fenología</h1><p>PWA de evaluación offline</p></div><form id="login"><label>Nombre<input name="name" required placeholder="Evaluador Demo"></label><label>DNI / PIN<input name="dni" required maxlength="8" inputmode="numeric"></label><button>Ingresar</button></form><small>Evaluador Demo / 87654321</small></section></main>`}
function shell(content){return `<header><div><b>🌱 Fenología</b><span>${session.name} · ${session.role}</span></div><nav><button data-view="home">Inicio</button><button data-view="evaluate">Registrar</button><button data-view="records">Registros</button>${session.role==='Administrador'?'<button data-view="admin">Administrar</button>':''}<button id="logout">Salir</button></nav></header>${content}`}
function home(){app.innerHTML=shell(`<main><h1>Panel principal</h1><div class="grid metrics"><article class="card"><b>${records.length}</b><span>Evaluaciones locales</span></article><article class="card"><b>${new Set(records.map(r=>r.lot)).size}</b><span>Lotes evaluados</span></article><article class="card"><b>${navigator.onLine?'En línea':'Sin internet'}</b><span>Estado de conexión</span></article></div><section class="card"><h2>Versión inicial</h2><p>La aplicación guarda la información en este dispositivo y funciona sin conexión después de la primera carga.</p></section></main>`)}
function varieties(field,lot){return assignments[lot]||catalogs.variedadesPorCampo[field]||[]}
function evaluate(){const fields=Object.keys(catalogs.lotesAgrupados);app.innerHTML=shell(`<main><h1>Registro de evaluación</h1><form id="evaluation" class="card form-grid"><label>Fecha<input type="date" name="date" required></label><label>Campaña<input name="campaign" required placeholder="2026-2027"></label><label>Campo<select name="field" required>${options(fields)}</select></label><label>Fundo<select name="farm" required disabled></select></label><label>Módulo<select name="module" required disabled></select></label><label>Turno-Lote<select name="lot" required disabled></select></label><label>Variedad<select name="variety" required disabled></select></label><label>Cuadrante<select name="quadrant" required>${options(catalogs.cuadrantes)}</select></label><div class="span"><h2>Estadios fenológicos</h2><div class="stage-grid">${stages.map(s=>`<label>${s}<input type="number" min="0" step="1" name="${s}"></label>`).join('')}</div></div><details class="span"><summary>Biometría · 35 frutos</summary><div class="fruit-grid">${Array.from({length:35},(_,i)=>`<fieldset><legend>Fruto ${i+1}</legend><input type="number" min="0" step="1" name="f${i+1}_dl" placeholder="D.L"><input type="number" min="0" step="1" name="f${i+1}_dea" placeholder="D.EA"><input type="number" min="0" step="1" name="f${i+1}_deb" placeholder="D.EB"></fieldset>`).join('')}</div></details><button class="span">Guardar evaluación</button></form></main>`);const f=document.querySelector('#evaluation');f.date.value=new Date().toISOString().slice(0,10);bindSelectors(f)}
function bindSelectors(f){const field=f.field,farm=f.farm,module=f.module,lot=f.lot,variety=f.variety;field.onchange=()=>{farm.innerHTML=options(Object.keys(catalogs.lotesAgrupados[field.value]||{}));farm.disabled=!field.value;module.innerHTML=options([]);lot.innerHTML=options([]);variety.innerHTML=options([])};farm.onchange=()=>{module.innerHTML=options(Object.keys(catalogs.lotesAgrupados[field.value]?.[farm.value]||{}));module.disabled=!farm.value};module.onchange=()=>{lot.innerHTML=options(catalogs.lotesAgrupados[field.value]?.[farm.value]?.[module.value]||[]);lot.disabled=!module.value};lot.onchange=()=>{variety.innerHTML=options(varieties(field.value,lot.value));variety.disabled=!lot.value}}
function recordsView(){app.innerHTML=shell(`<main><div class="title-row"><h1>Registros locales</h1><button id="export">Exportar CSV</button></div><section class="card table-wrap"><table><thead><tr><th>ID</th><th>Fecha</th><th>Lote</th><th>Variedad</th><th>Cuadrante</th><th>Planta</th></tr></thead><tbody>${records.map(r=>`<tr><td>${r.id}</td><td>${r.date}</td><td>${r.lot}</td><td>${r.variety}</td><td>${r.quadrant}</td><td>${r.plant}</td></tr>`).join('')||'<tr><td colspan="6">Sin registros</td></tr>'}</tbody></table></section></main>`)}
function admin(){const fields=Object.keys(catalogs.lotesAgrupados);app.innerHTML=shell(`<main><h1>Asignación de variedades por lote</h1><section class="card form-grid" id="assign"><label>Campo<select name="field">${options(fields)}</select></label><label>Fundo<select name="farm" disabled></select></label><label>Módulo<select name="module" disabled></select></label><label>Lote<select name="lot" disabled></select></label><div class="span" id="checks"></div><button class="span" id="save-assignment" type="button">Guardar asignación</button></section></main>`);const f=document.querySelector('#assign');bindSelectors({...f,field:f.field,farm:f.farm,module:f.module,lot:f.lot,variety:{innerHTML:'',disabled:true}});f.lot.onchange=()=>{const list=catalogs.variedadesPorCampo[f.field.value]||[];document.querySelector('#checks').innerHTML=list.map(v=>`<label class="check"><input type="checkbox" value="${v}" ${varieties(f.field.value,f.lot.value).includes(v)?'checked':''}>${v}</label>`).join('')}}
function exportCsv(){const h=['ID','FECHA','CAMPAÑA','CAMPO','FUNDO','MODULO','LOTE','VARIEDAD','CUADRANTE','PLANTA'];const rows=records.map(r=>h.map(k=>r[k.toLowerCase()]||r[k]||''));const csv=[h,...rows].map(r=>r.join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='fenologia.csv';a.click()}
function render(view='home'){if(!session)return login();({home,evaluate,records:recordsView,admin}[view]||home)()}
document.addEventListener('submit',e=>{if(e.target.id==='login'){e.preventDefault();const d=new FormData(e.target),u=users.find(x=>x.name.toLowerCase()===String(d.get('name')).toLowerCase()&&x.dni===d.get('dni'));if(!u)return say('Datos incorrectos');session=u;localStorage.setItem('fenologia-session',JSON.stringify(u));render()}else if(e.target.id==='evaluation'){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const plant=1+records.filter(r=>r.date===d.date&&r.lot===d.lot&&r.variety===d.variety&&r.quadrant===d.quadrant&&r.evaluator===session.name).length;records.push({...d,id:crypto.randomUUID(),plant,evaluator:session.name,createdAt:new Date().toISOString()});save();say(`Planta ${plant} guardada`);render('records')}});
document.addEventListener('click',e=>{const v=e.target.dataset.view;if(v)render(v);if(e.target.id==='logout'){localStorage.removeItem('fenologia-session');session=null;render()}if(e.target.id==='export')exportCsv();if(e.target.id==='save-assignment'){const f=document.querySelector('#assign');if(!f.lot.value)return say('Selecciona un lote');assignments[f.lot.value]=[...document.querySelectorAll('#checks input:checked')].map(x=>x.value);localStorage.setItem('fenologia-lot-varieties',JSON.stringify(assignments));say('Asignación guardada')}});
fetch('./data/catalogos.json').then(r=>r.json()).then(x=>{catalogs=x;render()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
